// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _191_MOMENT_4.Data;

#nullable disable

namespace _191_MOMENT_4.Migrations.AlbumLibrary
{
    [DbContext(typeof(AlbumLibraryContext))]
    [Migration("20230216062128_SecondDB")]
    partial class SecondDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("_191_MOMENT_4.Model.AlbumModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artists")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cathegory")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SongAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotLengthSec")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearPub")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("AlbumLibrary");
                });
#pragma warning restore 612, 618
        }
    }
}
