// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _191_MOMENT_4.Data;

#nullable disable

namespace _191_MOMENT_4.Migrations
{
    [DbContext(typeof(SongLibraryContext))]
    [Migration("20230215125437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("_191_MOMENT_4.Model.SongModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LengthSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SongTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("YearPub")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("SongLibrary");
                });
#pragma warning restore 612, 618
        }
    }
}
